apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "ec2-obs-deploy-apps"
  environment:
    cluster_type: ec2
    domain: vkpr.platform.vee.codes
    ingress_type: kong
    certificate_account_email: platformss@vee.codes
    certificate_environment_type: production
    grafana_obs_api: https://grafana.homolog-central-otlp.vkpr.platform.vee.codes
    public_ip: 34.203.88.204
  annotations:
    github.com/project-slug: veecode-homolog/ec2-obs-deploy-apps
    grafana/dashboard-selector: ec2-obs-deploy-apps
    grafana/alert-label-selector: "alertname=ec2-obs-deploy-apps"
    infracost/project: ec2-obs-deploy-apps
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,kubeconfig.yml,terraform-destroy.yml,infracost.yml
    cluster/instructions: "# Run the following commands to import the kubeconfig:\n  ssh -i ./cert.pem -o StrictHostKeyChecking=no $USERNAME@$34.203.88.204 \"mkdir -p .kube && k3d kubeconfig get k3s > ~/.kube/config\"\n  scp -i ./cert.pem $USERNAME@$34.203.88.204:~/.kube/config ~/.kube/config-ec2-obs-deploy-apps\n  yq -e 'del(.clusters[0].cluster.certificate-authority-data) | .clusters[0].cluster.insecure-skip-tls-verify=true | .clusters[].cluster.server |= sub(\"0.0.0.0\", \"34.203.88.204\")' -i ~/.kube/config-ec2-obs-deploy-apps\n  export KUBECONFIG=~/.kube/config-ec2-obs-deploy-apps\n  kubectl get pods -A\n"
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/platform_homolog_environment'
